NET/BUGTRACKER/redo/bugtrack/durand_yBugTrack/durand_yBugTrack/Models/ProjectModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace durand_yBugTrack.Models
{
    public class ProjectModel
    {
    }
}

NET/BUGTRACKER/redo/bugtrack/durand_yBugTrack/durand_yBugTrack/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace durand_yBugTrack.Models
{
    public class UserModel
    {
        public List<UserItem> userlist { get; set; }
    }

    public class UserItem
    {
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
    }
}

NET/BUGTRACKER/redo/bugtrack/durand_yBugTrack/durand_yBugTrack/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace durand_yBugTrack.Controllers
{
    public class IndexController : Controller
    {
        //
        // GET: /Index/

        public ActionResult Index()
        {
            return View();
        }

    }
}

NET/BUGTRACKER/redo/bugtrack/durand_yBugTrack/durand_yBugTrack/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace durand_yBugTrack.Controllers
{
    public class ProjectController : Controller
    {
        //
        // GET: /Project/

        public ActionResult Index()
        {
            return View();
        }

    }
}

NET/BUGTRACKER/redo/bugtrack/durand_yBugTrack/durand_yBugTrack/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace durand_yBugTrack.Controllers
{
    public class UserController : Controller
    {
        //
        // GET: /User/

        public ActionResult User()
        {
            durand_yBugTrack.Models.UserModel usermodel = new Models.UserModel();

            usermodel.userlist = BusinessManagement.User.getlist();

            return View("UserView", usermodel);
        }

    }
}

NET/BUGTRACKER/redo/bugtrack/durand_yBugTrack/durand_yBugTrack/Views/Index/Index.cshtml
@{
    ViewBag.Title = "index";
}

<h2>index</h2>
@Html.ActionLink("Voir les utilisateur", "User", "User");
<a>vers vue projet</a>

NET/BUGTRACKER/redo/bugtrack/durand_yBugTrack/durand_yBugTrack/Views/Project/ProjectView.cshtml
@{
    ViewBag.Title = "ProjectView";
}

<h2>ProjectView</h2>

NET/BUGTRACKER/redo/bugtrack/durand_yBugTrack/durand_yBugTrack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>

NET/BUGTRACKER/redo/bugtrack/durand_yBugTrack/durand_yBugTrack/Views/User/UserView.cshtml
@model durand_yBugtdack.Models.UserModel
@{
    ViewBag.Title = "UserView";
}

<h2>UserView</h2>
<div id="main">
    <table id="showdata">
        <thead>
            <tr>
            <td>Nom</td>
            <td>Prenom</td>
            <td>Mail</td>
            <td>Phone</td>
            </tr>
        </thead>
        <tbody>
            @foreach (durand_yBugTrack.Models.UserItem  user in Model.userlist)
            {
                <tr>
                    <td>@user.Name</td>
                    <td>@user.Firstname</td>
                    <td>@user.Mail</td>
                    <td>@user.Phone</td>
                </tr>
            }
        </tbody>
    </table>

</div>

NET/BUGTRACKER/redo/bugtrack/durand_yBugTrack/durand_yBugTrack/Views/index.cshtml
@{
    ViewBag.Title = "index";
}

<h2>index</h2>
<a>vers vue user</a>
<a>vers vue projet</a>